//go:build windows

package winusb

// Driver package (INF) generation. The INF binds inbox winusb.sys to the Jetson
// device IDs and exposes a stable device interface GUID so wendy can open the
// device by interface (SetupDiGetClassDevs with DIGCF_DEVICEINTERFACE).

import (
	"fmt"
	"strings"
)

// DeviceInterfaceGUID is wendy's stable WinUSB device-interface GUID for Jetson
// devices. The transport opens devices exposing this interface. Fixed forever.
const DeviceInterfaceGUID = "{9F5D2C3A-7B14-4E8D-9C6F-1A2B3C4D5E6F}"

// catalogFileName / infFileName are the package file names (co-located when staged).
const (
	catalogFileName = "wendy_jetson.cat"
	infFileName     = "wendy_jetson.inf"
)

// jetsonHardwareIDs are the device IDs the package binds WinUSB to: recovery
// (Orin/Thor) and the initrd-flash gadget. Pre-staging all three means the gadget
// binds automatically when it enumerates mid-flash, with no second prompt.
func jetsonHardwareIDs() []string {
	return []string{
		fmt.Sprintf("USB\\VID_%04X&PID_%04X", VendorNVIDIA, ProductThor),
		fmt.Sprintf("USB\\VID_%04X&PID_%04X", VendorNVIDIA, ProductOrin),
		fmt.Sprintf("USB\\VID_%04X&PID_%04X", VendorNVIDIA, ProductGadget),
	}
}

// generateINF returns the WinUSB INF text binding the Jetson hardware IDs.
func generateINF() string {
	// Per-model device lines shared by both arch sections.
	models := []struct{ desc, id string }{
		{"NVIDIA Jetson AGX Thor (recovery)", fmt.Sprintf("USB\\VID_%04X&PID_%04X", VendorNVIDIA, ProductThor)},
		{"NVIDIA Jetson Orin (recovery)", fmt.Sprintf("USB\\VID_%04X&PID_%04X", VendorNVIDIA, ProductOrin)},
		{"NVIDIA Jetson flashing gadget", fmt.Sprintf("USB\\VID_%04X&PID_%04X", VendorNVIDIA, ProductGadget)},
	}
	var devLines strings.Builder
	for i, m := range models {
		fmt.Fprintf(&devLines, "%%Dev%d.desc%% = USB_Install, %s\n", i, m.id)
	}
	var strLines strings.Builder
	for i, m := range models {
		fmt.Fprintf(&strLines, "Dev%d.desc = \"%s\"\n", i, m.desc)
	}

	// DriverVer date is fixed and in the past so PnP always prefers a device's
	// existing better driver if any, and never rejects ours as future-dated.
	return fmt.Sprintf(`; Wendy Labs — WinUSB binding for NVIDIA Jetson USB flashing.
; Generated by wendy; binds inbox winusb.sys to Jetson recovery + gadget IDs.
[Version]
Signature   = "$WINDOWS NT$"
Class       = USBDevice
ClassGuid   = {88BAE032-5A81-49F0-BC3D-A4FF138216D6}
Provider    = %%ProviderName%%
CatalogFile = %s
DriverVer   = 01/01/2026,1.0.0.0
PnpLockdown = 1

[Manufacturer]
%%ProviderName%% = Standard,NTamd64,NTarm64

[Standard.NTamd64]
%s
[Standard.NTarm64]
%s
[USB_Install]
Include = winusb.inf
Needs   = WINUSB.NT

[USB_Install.Services]
Include = winusb.inf
Needs   = WINUSB.NT.Services

[USB_Install.HW]
AddReg = Dev_AddReg

[Dev_AddReg]
HKR,,DeviceInterfaceGUIDs,0x00010000,"%s"

[Strings]
ProviderName = "Wendy Labs"
%s`,
		catalogFileName,
		devLines.String(),
		devLines.String(),
		DeviceInterfaceGUID,
		strLines.String(),
	)
}
