// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: wendycloud/v2/mesh.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

public import GRPCCore
public import GRPCProtobuf

// MARK: - wendycloud.v2.MeshRosterService

/// Namespace containing generated types for the "wendycloud.v2.MeshRosterService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Wendycloud_V2_MeshRosterService: Sendable {
    /// Service descriptor for the "wendycloud.v2.MeshRosterService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "wendycloud.v2.MeshRosterService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "GetMeshRoster" metadata.
        public enum GetMeshRoster: Sendable {
            /// Request type for "GetMeshRoster".
            public typealias Input = Wendycloud_V2_GetMeshRosterRequest
            /// Response type for "GetMeshRoster".
            public typealias Output = Wendycloud_V2_GetMeshRosterResponse
            /// Descriptor for "GetMeshRoster".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "wendycloud.v2.MeshRosterService"),
                method: "GetMeshRoster",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "wendycloud.v2.MeshRosterService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetMeshRoster.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "wendycloud.v2.MeshRosterService" service.
    public static let wendycloud_v2_MeshRosterService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "wendycloud.v2.MeshRosterService")
}

// MARK: wendycloud.v2.MeshRosterService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendycloud_V2_MeshRosterService {
    /// Streaming variant of the service protocol for the "wendycloud.v2.MeshRosterService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where the RPC expects only a single
    /// request or response message, you are responsible for ensuring your implementation
    /// maintains this invariant.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > MeshRosterService serves the minimal name directory the WendyOS mesh needs
    /// > to resolve <devicename>.<org-slug>.cloud.wendy.dev to a cloud asset id. It is
    /// > deliberately narrower than AssetService: only {name, asset_id} pairs plus the
    /// > caller's own org slug, scoped by the caller's asset-certificate identity.
    /// > 
    /// > The shape originates device-side in WendyOS (Proto/cloud/mesh.proto,
    /// > e926cb0dc), which is the only client; this is its first upstream home
    /// > (WDY-2824). Identities are v2 UUID strings.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "GetMeshRoster" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Wendycloud_V2_GetMeshRosterRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Wendycloud_V2_GetMeshRosterResponse` messages.
        func getMeshRoster(
            request: GRPCCore.StreamingServerRequest<Wendycloud_V2_GetMeshRosterRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Wendycloud_V2_GetMeshRosterResponse>
    }

    /// Service protocol for the "wendycloud.v2.MeshRosterService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > MeshRosterService serves the minimal name directory the WendyOS mesh needs
    /// > to resolve <devicename>.<org-slug>.cloud.wendy.dev to a cloud asset id. It is
    /// > deliberately narrower than AssetService: only {name, asset_id} pairs plus the
    /// > caller's own org slug, scoped by the caller's asset-certificate identity.
    /// > 
    /// > The shape originates device-side in WendyOS (Proto/cloud/mesh.proto,
    /// > e926cb0dc), which is the only client; this is its first upstream home
    /// > (WDY-2824). Identities are v2 UUID strings.
    public protocol ServiceProtocol: Wendycloud_V2_MeshRosterService.StreamingServiceProtocol {
        /// Handle the "GetMeshRoster" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V2_GetMeshRosterRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Wendycloud_V2_GetMeshRosterResponse` message.
        func getMeshRoster(
            request: GRPCCore.ServerRequest<Wendycloud_V2_GetMeshRosterRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Wendycloud_V2_GetMeshRosterResponse>
    }

    /// Simple service protocol for the "wendycloud.v2.MeshRosterService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > MeshRosterService serves the minimal name directory the WendyOS mesh needs
    /// > to resolve <devicename>.<org-slug>.cloud.wendy.dev to a cloud asset id. It is
    /// > deliberately narrower than AssetService: only {name, asset_id} pairs plus the
    /// > caller's own org slug, scoped by the caller's asset-certificate identity.
    /// > 
    /// > The shape originates device-side in WendyOS (Proto/cloud/mesh.proto,
    /// > e926cb0dc), which is the only client; this is its first upstream home
    /// > (WDY-2824). Identities are v2 UUID strings.
    public protocol SimpleServiceProtocol: Wendycloud_V2_MeshRosterService.ServiceProtocol {
        /// Handle the "GetMeshRoster" method.
        ///
        /// - Parameters:
        ///   - request: A `Wendycloud_V2_GetMeshRosterRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Wendycloud_V2_GetMeshRosterResponse` to respond with.
        func getMeshRoster(
            request: Wendycloud_V2_GetMeshRosterRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Wendycloud_V2_GetMeshRosterResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendycloud_V2_MeshRosterService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Wendycloud_V2_MeshRosterService.Method.GetMeshRoster.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Wendycloud_V2_GetMeshRosterRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Wendycloud_V2_GetMeshRosterResponse>(),
            handler: { request, context in
                try await self.getMeshRoster(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendycloud_V2_MeshRosterService.ServiceProtocol {
    public func getMeshRoster(
        request: GRPCCore.StreamingServerRequest<Wendycloud_V2_GetMeshRosterRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Wendycloud_V2_GetMeshRosterResponse> {
        let response = try await self.getMeshRoster(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendycloud_V2_MeshRosterService.SimpleServiceProtocol {
    public func getMeshRoster(
        request: GRPCCore.ServerRequest<Wendycloud_V2_GetMeshRosterRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Wendycloud_V2_GetMeshRosterResponse> {
        return GRPCCore.ServerResponse<Wendycloud_V2_GetMeshRosterResponse>(
            message: try await self.getMeshRoster(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: wendycloud.v2.MeshRosterService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendycloud_V2_MeshRosterService {
    /// Generated client protocol for the "wendycloud.v2.MeshRosterService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > MeshRosterService serves the minimal name directory the WendyOS mesh needs
    /// > to resolve <devicename>.<org-slug>.cloud.wendy.dev to a cloud asset id. It is
    /// > deliberately narrower than AssetService: only {name, asset_id} pairs plus the
    /// > caller's own org slug, scoped by the caller's asset-certificate identity.
    /// > 
    /// > The shape originates device-side in WendyOS (Proto/cloud/mesh.proto,
    /// > e926cb0dc), which is the only client; this is its first upstream home
    /// > (WDY-2824). Identities are v2 UUID strings.
    public protocol ClientProtocol: Sendable {
        /// Call the "GetMeshRoster" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V2_GetMeshRosterRequest` message.
        ///   - serializer: A serializer for `Wendycloud_V2_GetMeshRosterRequest` messages.
        ///   - deserializer: A deserializer for `Wendycloud_V2_GetMeshRosterResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        func getMeshRoster<Result>(
            request: GRPCCore.ClientRequest<Wendycloud_V2_GetMeshRosterRequest>,
            serializer: some GRPCCore.MessageSerializer<Wendycloud_V2_GetMeshRosterRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Wendycloud_V2_GetMeshRosterResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V2_GetMeshRosterResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "wendycloud.v2.MeshRosterService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > MeshRosterService serves the minimal name directory the WendyOS mesh needs
    /// > to resolve <devicename>.<org-slug>.cloud.wendy.dev to a cloud asset id. It is
    /// > deliberately narrower than AssetService: only {name, asset_id} pairs plus the
    /// > caller's own org slug, scoped by the caller's asset-certificate identity.
    /// > 
    /// > The shape originates device-side in WendyOS (Proto/cloud/mesh.proto,
    /// > e926cb0dc), which is the only client; this is its first upstream home
    /// > (WDY-2824). Identities are v2 UUID strings.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetMeshRoster" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Wendycloud_V2_GetMeshRosterRequest` message.
        ///   - serializer: A serializer for `Wendycloud_V2_GetMeshRosterRequest` messages.
        ///   - deserializer: A deserializer for `Wendycloud_V2_GetMeshRosterResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response and returns its result to
        ///       the caller. Returning from the closure will cancel the RPC if it hasn't
        ///       already finished.
        /// - Returns: The result of `handleResponse`.
        public func getMeshRoster<Result>(
            request: GRPCCore.ClientRequest<Wendycloud_V2_GetMeshRosterRequest>,
            serializer: some GRPCCore.MessageSerializer<Wendycloud_V2_GetMeshRosterRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Wendycloud_V2_GetMeshRosterResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V2_GetMeshRosterResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Wendycloud_V2_MeshRosterService.Method.GetMeshRoster.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendycloud_V2_MeshRosterService.ClientProtocol {
    /// Call the "GetMeshRoster" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Wendycloud_V2_GetMeshRosterRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func getMeshRoster<Result>(
        request: GRPCCore.ClientRequest<Wendycloud_V2_GetMeshRosterRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V2_GetMeshRosterResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getMeshRoster(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Wendycloud_V2_GetMeshRosterRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Wendycloud_V2_GetMeshRosterResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Wendycloud_V2_MeshRosterService.ClientProtocol {
    /// Call the "GetMeshRoster" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response and returns its result to
    ///       the caller. Returning from the closure will cancel the RPC if it hasn't
    ///       already finished.
    /// - Returns: The result of `handleResponse`.
    public func getMeshRoster<Result>(
        _ message: Wendycloud_V2_GetMeshRosterRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Wendycloud_V2_GetMeshRosterResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Wendycloud_V2_GetMeshRosterRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getMeshRoster(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}